spring:
  mvc:
    favicon:
      enabled: false
  jackson:
    default-property-inclusion: NON_NULL
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-34-247-172-149.eu-west-1.compute.amazonaws.com/d7l17il1mhmhk3
    hikari:
      username: skpfwyatodzqmc
      password: fd77f6f64fa594e261c7db8aee31470f0c955a01b5d5590de18027971286c661
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
#    open-in-view: true
#    generate-ddl: true


management:
  endpoints:
    web:
      path-mapping:
        health: healthcheck
      base-path: /_monitoring
  endpoint:
    health:
      show-details: never
      enabled: true

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: application/json